// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForCreateOrderProducts implements pgx.CopyFromSource.
type iteratorForCreateOrderProducts struct {
	rows                 []CreateOrderProductsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateOrderProducts) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateOrderProducts) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].OrderID,
		r.rows[0].ProductID,
		r.rows[0].OrderedAmount,
	}, nil
}

func (r iteratorForCreateOrderProducts) Err() error {
	return nil
}

func (q *Queries) CreateOrderProducts(ctx context.Context, arg []CreateOrderProductsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"order_products"}, []string{"order_id", "product_id", "ordered_amount"}, &iteratorForCreateOrderProducts{rows: arg})
}
