// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateLog(ctx context.Context, arg CreateLogParams) error
	CreateOrder(ctx context.Context, customerID int64) (Order, error)
	CreateOrderProducts(ctx context.Context, arg []CreateOrderProductsParams) (int64, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	DeleteCustomer(ctx context.Context, id int64) error
	DeleteOrder(ctx context.Context, id int64) error
	DeleteProduct(ctx context.Context, id int64) error
	GetCustomerByUsername(ctx context.Context, username string) (Customer, error)
	GetOrder(ctx context.Context, arg GetOrderParams) (Order, error)
	GetProduct(ctx context.Context, id int64) (Product, error)
	GetTotalPrice(ctx context.Context, orderID int64) (int64, error)
	ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error)
	ListOrders(ctx context.Context, customerID int64) ([]Order, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	SoftDeleteOrder(ctx context.Context, arg SoftDeleteOrderParams) (Order, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
}

var _ Querier = (*Queries)(nil)
